#!/usr/bin/env python3
"""Generate a fully synthetic fintech dataset as a Postgres SQL dump.

Deterministic (seeded) and dependency-free — uses only the Python standard
library, so `python3 database/seed.py` works anywhere. Output is written next to
this file as ``finpulse_seed.sql`` and mounted into Postgres at container init
AFTER ``schema.sql`` and BEFORE ``read_only_user.sql``.

Every value here is invented. There is no real or confidential data.

Tune sizes with env vars: FINPULSE_CUSTOMERS, FINPULSE_TRANSACTIONS,
FINPULSE_LOANS, FINPULSE_TICKETS, FINPULSE_MERCHANTS.
"""

from __future__ import annotations

import os
import random
from datetime import datetime, timedelta, date
from pathlib import Path

random.seed(42)

# --- knobs -----------------------------------------------------------------
N_CUSTOMERS = int(os.environ.get("FINPULSE_CUSTOMERS", 4000))
N_MERCHANTS = int(os.environ.get("FINPULSE_MERCHANTS", 400))
N_TRANSACTIONS = int(os.environ.get("FINPULSE_TRANSACTIONS", 60000))
N_LOANS = int(os.environ.get("FINPULSE_LOANS", 1500))
N_TICKETS = int(os.environ.get("FINPULSE_TICKETS", 5000))

# Data spans ~24 months ending at a fixed reference date (reproducible dump).
END = datetime(2026, 6, 30, 12, 0, 0)
START = END - timedelta(days=730)
BATCH = 500

OUT = Path(__file__).with_name("finpulse_seed.sql")

# --- vocab -----------------------------------------------------------------
FIRST = (
    "James Mary John Patricia Robert Jennifer Michael Linda David Elizabeth William Barbara "
    "Aisha Omar Sofia Liam Noah Emma Olivia Ava Mia Lucas Mateo Hugo Chloe Yuki Hana Wei Li "
    "Ivan Anna Diego Carmen Fatima Yusuf Priya Arjun Sven Greta Pierre Camille Marco Giulia"
).split()
LAST = (
    "Smith Johnson Williams Brown Jones Garcia Miller Davis Rodriguez Martinez Hernandez Lopez "
    "Khan Ali Ahmed Nguyen Tran Kim Park Chen Wang Singh Patel Schmidt Mueller Rossi Bianchi "
    "Dubois Laurent Petrov Ivanova Silva Santos Andersson Eriksson Kowalski Novak Tanaka Sato"
).split()
PLACES = [
    ("New York", "USA"), ("Chicago", "USA"), ("San Francisco", "USA"), ("Austin", "USA"),
    ("London", "UK"), ("Manchester", "UK"), ("Berlin", "Germany"), ("Munich", "Germany"),
    ("Paris", "France"), ("Madrid", "Spain"), ("Barcelona", "Spain"), ("Toronto", "Canada"),
    ("Sydney", "Australia"), ("Singapore", "Singapore"), ("Dubai", "UAE"), ("Amsterdam", "Netherlands"),
]
CATEGORIES = [
    "Groceries", "Dining", "Travel", "Electronics", "Utilities", "Entertainment",
    "Healthcare", "Transport", "Fashion", "Education", "Subscriptions", "Home",
]
MERCH_PREFIX = ("Urban Fresh Prime Metro Nova Blue Green Swift Bright Daily Global Smart "
                "Peak Core True City Sunny Royal Apex Pure").split()
MERCH_SUFFIX = ("Mart Store Hub Shop Market Express Place Co Goods Outlet Center Point "
                "Works Studio Labs Group Foods Wear Tech Travel").split()


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def ts(dt: datetime) -> str:
    return "'" + dt.strftime("%Y-%m-%d %H:%M:%S") + "+00'"


def dd(d: date) -> str:
    return "'" + d.strftime("%Y-%m-%d") + "'"


def b(v: bool) -> str:
    return "true" if v else "false"


def rand_dt(a: datetime, c: datetime) -> datetime:
    span = max((c - a).total_seconds(), 1)
    return a + timedelta(seconds=random.uniform(0, span))


def recent_biased_dt(a: datetime, c: datetime) -> datetime:
    """Datetime skewed toward the recent end (drives a 'growth' trend)."""
    span = max((c - a).total_seconds(), 1)
    frac = random.random() ** 0.6  # bias toward 1.0 (recent)
    return a + timedelta(seconds=frac * span)


def w(pop, weights):
    return random.choices(pop, weights=weights, k=1)[0]


class Writer:
    def __init__(self, fh):
        self.fh = fh

    def insert(self, table: str, columns: str, rows):
        buf, n = [], 0
        for r in rows:
            buf.append("(" + ",".join(r) + ")")
            n += 1
            if len(buf) >= BATCH:
                self._flush(table, columns, buf)
                buf = []
        if buf:
            self._flush(table, columns, buf)
        return n

    def _flush(self, table, columns, buf):
        self.fh.write(f"INSERT INTO {table} ({columns}) VALUES\n")
        self.fh.write(",\n".join(buf))
        self.fh.write(";\n")


def main() -> None:
    fh = OUT.open("w", encoding="utf-8")
    fh.write("-- AUTO-GENERATED by database/seed.py — fully synthetic demo data. Do not edit.\n")
    fh.write("BEGIN;\n")
    out = Writer(fh)

    # Customers --------------------------------------------------------------
    customers = []  # (id, created_at)
    def cust_rows():
        for cid in range(1, N_CUSTOMERS + 1):
            fn, ln = random.choice(FIRST), random.choice(LAST)
            city, country = random.choice(PLACES)
            created = recent_biased_dt(START, END)
            customers.append((cid, created))
            email = f"{fn.lower()}.{ln.lower()}{cid}@example.com"
            phone = "+1" + "".join(str(random.randint(0, 9)) for _ in range(10))
            segment = w(["retail", "sme", "premium"], [70, 22, 8])
            kyc = w(["verified", "pending", "rejected"], [85, 12, 3])
            yield [
                str(cid), q(f"{fn} {ln}"), q(email), q(phone), q(country), q(city),
                q(segment), q(kyc), b(random.random() < 0.92), ts(created), b(False),
            ]
    out.insert("fin.customers",
               "id, full_name, email, phone, country, city, segment, kyc_status, is_active, created_at, is_deleted",
               cust_rows())

    # Merchant categories ----------------------------------------------------
    out.insert("fin.merchant_categories", "id, name",
               ([str(i), q(name)] for i, name in enumerate(CATEGORIES, start=1)))

    # Merchants --------------------------------------------------------------
    merchants = []  # id
    def merch_rows():
        for mid in range(1, N_MERCHANTS + 1):
            name = f"{random.choice(MERCH_PREFIX)} {random.choice(MERCH_SUFFIX)}"
            cat = random.randint(1, len(CATEGORIES))
            _, country = random.choice(PLACES)
            merchants.append(mid)
            yield [str(mid), q(name), str(cat), q(country), b(False)]
    out.insert("fin.merchants", "id, name, category_id, country, is_deleted", merch_rows())

    # Accounts ---------------------------------------------------------------
    accounts = []  # (id, customer_id, currency, opened_at, status)
    acc_id = 0
    def acc_rows():
        nonlocal acc_id
        for cid, created in customers:
            n = w([1, 2, 3], [55, 35, 10])
            for _ in range(n):
                acc_id += 1
                opened = rand_dt(created, END)
                currency = w(["USD", "EUR", "GBP"], [70, 20, 10])
                status = w(["active", "frozen", "closed"], [90, 4, 6])
                atype = w(["checking", "savings", "credit"], [55, 35, 10])
                balance = round(random.lognormvariate(7.8, 1.1), 2)
                accounts.append((acc_id, cid, currency, opened, status))
                yield [
                    str(acc_id), str(cid), q(atype), q(currency), f"{balance:.2f}",
                    q(status), ts(opened), b(False),
                ]
    out.insert("fin.accounts",
               "id, customer_id, account_type, currency, balance, status, opened_at, is_deleted",
               acc_rows())

    # Cards ------------------------------------------------------------------
    cards_by_account: dict[int, list[int]] = {}
    card_id = 0
    def card_rows():
        nonlocal card_id
        for aid, cid, currency, opened, status in accounts:
            if status == "closed":
                continue
            for _ in range(w([0, 1, 2], [15, 60, 25])):
                card_id += 1
                cards_by_account.setdefault(aid, []).append(card_id)
                ctype = w(["debit", "credit", "virtual"], [60, 25, 15])
                network = w(["visa", "mastercard", "amex"], [50, 40, 10])
                cstatus = w(["active", "blocked", "expired"], [88, 5, 7])
                issued = rand_dt(opened, END)
                yield [
                    str(card_id), str(aid), q(ctype), q(network), q(cstatus),
                    ts(issued), b(False),
                ]
    out.insert("fin.cards", "id, account_id, card_type, network, status, issued_at, is_deleted",
               card_rows())

    # Transactions -----------------------------------------------------------
    fraud_base = {"pos": 0.003, "online": 0.015, "atm": 0.006, "transfer": 0.004}
    def tx_rows():
        for tid in range(1, N_TRANSACTIONS + 1):
            aid, cid, currency, opened, status_a = random.choice(accounts)
            channel = w(["pos", "online", "atm", "transfer"], [45, 35, 12, 8])
            direction = w(["debit", "credit"], [82, 18])
            amount = round(random.lognormvariate(3.5, 1.0), 2)
            if channel == "atm":
                amount = float(round(amount / 10.0) * 10 or 10)
            status = w(["completed", "pending", "failed", "reversed"], [92, 2, 4, 2])
            is_fraud = random.random() < fraud_base[channel]
            card_id_val = "NULL"
            cards = cards_by_account.get(aid)
            if cards and channel in ("pos", "online") and random.random() < 0.85:
                card_id_val = str(random.choice(cards))
            merch_val = str(random.choice(merchants)) if channel in ("pos", "online") else "NULL"
            created = rand_dt(opened, END)
            yield [
                str(tid), str(aid), card_id_val, merch_val, f"{amount:.2f}", q(currency),
                q(direction), q(channel), q(status), b(is_fraud), ts(created), b(False),
            ]
    out.insert("fin.transactions",
               "id, account_id, card_id, merchant_id, amount, currency, direction, channel, status, is_fraud, created_at, is_deleted",
               tx_rows())

    # Loans ------------------------------------------------------------------
    loan_specs = {
        # product: (principal_mu, principal_sigma, rate_lo, rate_hi, term_choices, default_w)
        "personal": (8.9, 0.5, 6.0, 18.0, [12, 24, 36, 48, 60], 9),
        "auto": (10.1, 0.4, 4.0, 11.0, [36, 48, 60, 72], 6),
        "mortgage": (12.0, 0.4, 3.0, 7.0, [120, 180, 240, 360], 3),
        "business": (11.0, 0.6, 7.0, 16.0, [12, 24, 36, 60, 84], 11),
    }
    loans = []  # (id, principal, term, disbursed, status)
    def loan_rows():
        for lid in range(1, N_LOANS + 1):
            cid, _ = random.choice(customers)
            product = w(list(loan_specs), [45, 25, 15, 15])
            mu, sigma, rlo, rhi, terms, dw = loan_specs[product]
            principal = round(random.lognormvariate(mu, sigma), 2)
            rate = round(random.uniform(rlo, rhi), 2)
            term = random.choice(terms)
            status = w(["active", "paid", "defaulted"], [70, 30 - dw, dw])
            disbursed = rand_dt(START, END)
            loans.append((lid, principal, term, disbursed, status))
            yield [
                str(lid), str(cid), q(product), f"{principal:.2f}", f"{rate:.2f}",
                str(term), q(status), ts(disbursed), b(False),
            ]
    out.insert("fin.loans",
               "id, customer_id, product, principal, interest_rate, term_months, status, disbursed_at, is_deleted",
               loan_rows())

    # Loan payments ----------------------------------------------------------
    pay_id = 0
    def payment_rows():
        nonlocal pay_id
        for lid, principal, term, disbursed, lstatus in loans:
            monthly = round(principal / term * 1.05, 2)
            elapsed = int((END - disbursed).days // 30)
            count = min(term, elapsed, 18)
            for k in range(1, count + 1):
                pay_id += 1
                due = (disbursed + timedelta(days=30 * k)).date()
                if lstatus == "paid":
                    pstatus, paid = "paid", due
                elif lstatus == "defaulted" and k > max(1, count - 3):
                    pstatus, paid = w(["missed", "late"], [70, 30]), None
                else:
                    pstatus = w(["paid", "late", "missed"], [88, 9, 3])
                    paid = due + timedelta(days=random.randint(0, 6)) if pstatus != "missed" else None
                yield [
                    str(pay_id), str(lid), f"{monthly:.2f}", dd(due),
                    (dd(paid) if paid else "NULL"), q(pstatus), b(False),
                ]
    out.insert("fin.loan_payments", "id, loan_id, amount, due_date, paid_date, status, is_deleted",
               payment_rows())

    # Support tickets --------------------------------------------------------
    def ticket_rows():
        for tid in range(1, N_TICKETS + 1):
            cid, created_c = random.choice(customers)
            created = rand_dt(created_c, END)
            category = w(["card", "payments", "account", "loan", "app", "fraud"],
                         [28, 26, 16, 10, 14, 6])
            priority = w(["low", "medium", "high", "urgent"], [35, 40, 18, 7])
            status = w(["open", "in_progress", "resolved", "closed"], [15, 15, 55, 15])
            resolved = "NULL"
            if status in ("resolved", "closed"):
                resolved = ts(created + timedelta(hours=random.randint(2, 240)))
            yield [
                str(tid), str(cid), q(category), q(priority), q(status), ts(created),
                resolved, b(False),
            ]
    out.insert("fin.support_tickets",
               "id, customer_id, category, priority, status, created_at, resolved_at, is_deleted",
               ticket_rows())

    # Keep BIGINT PK sequences (none here — ids are explicit) and finish.
    fh.write("COMMIT;\n")
    fh.close()

    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"Wrote {OUT} ({size_mb:.1f} MB)")
    print(f"  customers={N_CUSTOMERS} accounts={len(accounts)} cards={card_id} "
          f"merchants={N_MERCHANTS} transactions={N_TRANSACTIONS} loans={N_LOANS} "
          f"loan_payments={pay_id} tickets={N_TICKETS}")


if __name__ == "__main__":
    main()
